baseURL = "https://example.com/"
languageCode = "en"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"

[params]
    phone = "02-82581918"
    address = "22043 新北市板橋區雙十路2段143號4樓"
    year = 2023
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/banner.png"
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[params.google.analytics]
    trackerID = "G-TSZDRRZVWX"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/swcpea/"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"

[[params.social]]
	title = "email"
	url = "mailto:tpswcpea@seed.net.tw"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"